<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.fundaciobit.pluginsib.tipusdocumental</groupId>
    <artifactId>pluginsib-tipusdocumental</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>PluginsIB - TipusDocumental</name>

    <parent>
        <artifactId>caib-artifacts-jdk11-jboss72or74-with-github-governib-distribution</artifactId>
        <groupId>es.caib.maven</groupId>
        <version>1.0.1-SNAPSHOT</version>
    </parent>

    <modules>
        <module>api</module>
        <module>portafib</module>
        <module>database</module>
        <module>nti</module>
    </modules>
    
    <developers>
        <developer>
            <id>anadal-fundaciobit</id>
            <name>Antoni Nadal</name>
        </developer>
    </developers>

    <organization>
        <name>Fundació Bit - Govern Digital</name>
        <url>https://governdigital.fundaciobit.org</url>
    </organization>

    <licenses>
        <license>
            <name>European Union Public Licence (EUPL v1.2)</name>
            <url>
                https://joinup.ec.europa.eu/sites/default/files/custom-page/attachment/eupl_v1.2_es.pdf</url>
        </license>
    </licenses>
    
    <repositories>
        <repository>
            <id>github_governib_maven</id>
            <name>GitHub GovernIB Maven Repository</name>
            <url>https://governib.github.io/maven/maven/</url>
        </repository>
    </repositories>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>commons-io</groupId>
                <artifactId>commons-io</artifactId>
                <version>2.2</version>
                <!-- <version>2.5.0.redhat-3</version> -->
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.fundaciobit.pluginsib.core.v3</groupId>
            <artifactId>pluginsib-core</artifactId>
            <version>3.0.0-SNAPSHOT</version>
        </dependency>
    </dependencies>


    <!--   COM UTILITZAR: AFEGIR AQUEST CODI AL pom.xml    -->
    <!--
    <repositories>
        <repository>
            <id>github-governib-maven-repos</id>
            <name>GitHub GovernIB Maven Repository</name>
            <url>http://GovernIB.github.io/maven/maven/</url>
        </repository>
    </repositories>
    -->
</project>
