/*
 * OpenAPI
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.api;

import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.services.ApiException;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.servicesforutilitatsfirma.ApiClientWithJsonSupport;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.CertificateTypeEidasConstants;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.CertificateTypeMineturConstants;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.CommonInfo;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.DocumentaryType;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.FileInfoSignatureV2;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.KeyValue;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.ProcessStatus;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.Profile;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.RestExceptionInfo;

import java.util.Set;

import javax.ws.rs.core.Response.Status;

import org.jboss.logging.Logger;

import com.fasterxml.jackson.databind.ObjectMapper;

import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.SignDocumentRequestV2;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.SignModeConstants;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.SignatureRequestedInformation;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.SignedDocumentInformation;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.SignedDocumentResponseMultipart;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.SignedFileInfo;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.StatusConstants;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.UpgradeResponseMultipart;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.ValidateSignatureResponse;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.ValidationStatusConstants;

import java.util.ArrayList;
import java.util.List;
import java.util.Properties;

/**
 * UtilitatsFirmaV2ApiTest
 * API tests for UtilitatsFirmaV2Api
 *
 * @author anadal (u80067)
 * 25 feb 2026 9:25:20
 */
class UtilitatsFirmaV2ApiTest  {
    
    protected Logger log = Logger.getLogger(getClass());

    public static void main(String[] args) {
        UtilitatsFirmaV2ApiTest test = new UtilitatsFirmaV2ApiTest();
        try {

            test.testTipusDocumentalList();

            test.testTipusDocumentalListWithNotValidAppUser();

            test.testPerfilsDeFirmaList();

            test.testAvailableLanguages();

            test.testSignatureServerPAdES();

            test.testSignatureServerPAdESStatus401_Unathorized();

            test.testSignatureServerPAdESErrorFirmant();

            test.testUpgradePAdESSignature();

            test.testValidateSignatures();

        } catch (ApiException e) {
            test.processApiException(e, "Tests de Firma en Servidor", true);
        } catch (Exception e) {
            e.printStackTrace(System.err);
        }
    }

    public void testSignatureServerPAdESStatus401_Unathorized() throws ApiException, Exception {

        final String testName = "Firma en Servidor - Error 401- UNAUTHORIZED";
        final Integer expectedError = 401;

        ApiClientWithJsonSupport apiClient = getApiClient();
        apiClient.setPassword("badpassword");
        UtilitatsFirmaV2Api apiError = new UtilitatsFirmaV2Api(apiClient);

        final boolean useTimeStamp = false;

        //Document fileToSign = llegirFitxer("./testfiles/hola.pdf", "application/pdf");
        File fileToSign = new File("./testfiles_serversignature/hola.pdf");
        internalTestSignatureServerPAdES(testName, expectedError, apiError, fileToSign, useTimeStamp);

        System.out.println("Test OK");

    }

    public void testSignatureServerPAdESErrorFirmant() throws ApiException, Exception {

        final String testName = "Firma en Servidor - Error Firmant xml amb PAdES";
        final Integer expectedError = null;

        UtilitatsFirmaV2Api api = getApi();

        final boolean useTimeStamp = false;

        try {
            //Document fileToSign = llegirFitxer("./src/main/resources/sample.xml", "application/xml");
            File fileToSign = new File("./testfiles_serversignature/sample.xml");
            internalTestSignatureServerPAdES(testName, expectedError, api, fileToSign, useTimeStamp);
            throw new Exception("S'ha enviat un fitxer XML per firma en format PAdES i s'esperava un error.");
        } catch (EstatFinalNoOK e) {

            if (StatusConstants.STATUS_FINAL_ERROR.getValue().equals(e.getInternalCode())) {
                System.out.println("Test OK");
            } else {
                throw new Exception("S'ha rebut un error de EstatFinalNoOK però s'esperava un internalCode "
                        + StatusConstants.STATUS_FINAL_ERROR.getValue() + " però s'ha rebut un " + e.getInternalCode());
            }
        }

    }

    /**
     * Operacio de firma simple en servidor d&#39;un document PDF
     *
     * @throws ApiException if the Api call fails
     */
    public void testSignatureServerPAdES() throws ApiException, Exception {

        final String testName = "Firma PAdES en Servidor";
        final Integer expectedError = null;

        UtilitatsFirmaV2Api api = getApi();

        final boolean useTimeStamp = false;

        List<File> documents = getPdfDocumentsToSign(getConfigProperties());
        for (File document : documents) {
            internalTestSignatureServerPAdES(testName, expectedError, api, document, useTimeStamp);
        }

    }

    public void testSignatureServerPadesWithTimestamp() throws ApiException, Exception {

        final String testName = "Firma PAdES en Servidor amb Segell de Temps";
        final Integer expectedError = null;

        UtilitatsFirmaV2Api api = getApi();

        final boolean useTimeStamp = true;

        List<File> documents = getPdfDocumentsToSign(getConfigProperties());
        for (File document : documents) {
            internalTestSignatureServerPAdES(testName, expectedError, api, document, useTimeStamp);
        }

    }

    protected SignedDocumentResponseMultipart internalTestSignatureServerPAdES(final String testName,
            final Integer expectedError, UtilitatsFirmaV2Api api, File file, boolean useTimeStamp)
            throws Exception, ApiException {
        Properties prop = getConfigProperties();

        String languageUI = prop.getProperty("languageUI", "ca");

        String perfil = prop.getProperty(PROFILE_PADES_PROPERTY);
        if (perfil == null || perfil.trim().isEmpty()) {
            throw new Exception("La propietat " + PROFILE_PADES_PROPERTY + " no està definida al fitxer "
                    + getConfigPropertiesFile());
        }

        // Document fileToSign = llegirFitxer(file == null ? "src/main/resources/hola-test.pdf" : file, "application/pdf");

        System.out.println(" PERFIL => " + perfil);
        System.out.println(" FILE NOM => " + file.getName());
        return internalSignDocument(api, perfil, file, languageUI, testName, expectedError, useTimeStamp);
    }

    protected SignedDocumentResponseMultipart internalTestSignatureServerCAdES(final String testName,
            final Integer expectedError, UtilitatsFirmaV2Api api, File file, boolean useTimeStamp)
            throws Exception, ApiException {
        Properties prop = getConfigProperties();

        String languageUI = prop.getProperty("languageUI", "ca");

        String perfil = prop.getProperty(PROFILE_CADES_PROPERTY);
        if (perfil == null || perfil.trim().isEmpty()) {
            throw new Exception("La propietat " + PROFILE_PADES_PROPERTY + " no està definida al fitxer "
                    + getConfigPropertiesFile());
        }

        // Document fileToSign = llegirFitxer(file == null ? "src/main/resources/hola-test.pdf" : file, "application/pdf");

        System.out.println(" PERFIL => " + perfil);
        System.out.println(" FILE NOM => " + file.getName());
        return internalSignDocument(api, perfil, file, languageUI, testName, expectedError, useTimeStamp);
    }

    protected SignedDocumentResponseMultipart internalSignDocument(UtilitatsFirmaV2Api api, final String perfil, File file,
            String languageUI, String testName, Integer expectedError, boolean useTimeStamp)
            throws ApiException, Exception {

        System.out.println("============================ " + testName + " ============================");
        try {
            String signID = "1";
            String name = file.getName();
            String reason = "Per aprovar pressuposts";
            String location = "Palma";

            int signNumber = 1;
            String languageSign = "ca";
            long tipusDocumentalID = 99; // =TD99

            String alias = getConfigProperties().getProperty("alias");

            FileInfoSignatureV2 fileInfoSignature = new FileInfoSignatureV2();
            //fileInfoSignature.setFileToSign(fileToSign);
            fileInfoSignature.setSignID(signID);
            fileInfoSignature.setName(name);
            fileInfoSignature.setReason(reason);
            fileInfoSignature.setLocation(location);
            fileInfoSignature.setSignNumber(signNumber);
            fileInfoSignature.setLanguageSign(languageSign);

            fileInfoSignature.setDocumentType(tipusDocumentalID);

            fileInfoSignature.setUseTimeStamp(useTimeStamp);

            // Es la configuració del Servidor (deixam el valor per defecte)
            String username = alias;
            String administrationID = null;
            String signerEmail = null;

            CommonInfo commonInfo = new CommonInfo();
            commonInfo.setSignProfile(perfil);
            commonInfo.setLanguageUI(languageUI);
            commonInfo.setUsername(username);
            commonInfo.setAdministrationID(administrationID);
            commonInfo.setSignerEmail(signerEmail);

            System.out.println("languageUI = |" + languageUI + "|");

            SignDocumentRequestV2 signature = new SignDocumentRequestV2();

            signature.setCommonInfo(commonInfo);
            signature.setFileInfoSignature(fileInfoSignature);

            System.out.println("\n\nEnviant petició de firma al servidor " + signature.getCommonInfo());

            SignedDocumentResponseMultipart multipartResults = api.signdocument(signature, file, null);
            
            SignedDocumentInformation fullResults = multipartResults.getSignedDocumentInformation();

            System.out.println(fullResults.getSignPlugin());

            ProcessStatus transactionStatus = fullResults.getStatus();

            int status = transactionStatus.getStatus();

            if (status == (int) StatusConstants.STATUS_INITIALIZING.getValue()) {
                throw new EstatFinalNoOK(status, "Rebut estat Initializing ...Unknown Error (???)");

            } else if (status == (int) StatusConstants.STATUS_IN_PROGRESS.getValue()) {
                throw new EstatFinalNoOK(status, "Rebut estat IN_PROGRESS ... Unknown Error (????) ");

            } else if (status == (int) StatusConstants.STATUS_FINAL_ERROR.getValue()) {

                throw new EstatFinalNoOK(status, "Rebut estat ERROR: " + transactionStatus.getErrorMessage(),
                        transactionStatus.getErrorStackTrace());

            } else if (status == (int) StatusConstants.STATUS_CANCELLED.getValue()) {
                throw new EstatFinalNoOK(status, "Rebut estat CANCELED: S'ha cancel·lat el procés de firmat.");

            } else if (status == (int) StatusConstants.STATUS_FINAL_OK.getValue()) {

                System.out.println(" ========= RESULTAT  =========");

                {

                    SignedFileInfo signedFileInfo = fullResults.getSignedFileInfo();
                    if (signedFileInfo != null) {
                        System.out.println(fullResults.getSignedFileInfo());
                    } else {
                        System.out.println("  Signed File Info: NULL");
                    }

                    System.err.println("  RESULT: OK");
                    File fsf = multipartResults.getSignedFile();
                    
                    System.out.println("  Fitxer " + fsf);
                    
                    File result = new File(getResultsDirectory(), testName.replace(' ', '-') + "_" + fullResults.getSignedFileName());
                    
                    result.delete(); // Eliminar el fitxer si ja existeix
                    fsf.renameTo(result);
                    
                    /*
                    FileOutputStream fos = new FileOutputStream(result);
                    fos.write(fsf.getData());
                    fos.flush();
                    fos.close();
                    */
                    System.out.println("  RESULT: Fitxer signat guardat en '" + result.getAbsolutePath() + "'");

                    return multipartResults;

                } // Final for de fitxers firmats
            } else {
                throw new EstatFinalNoOK(null, "Rebut estat desconegut (" + status + ")");
            } // Final for de fitxers firmats
              // Final Case Firma OK
              // Final Switch Firma
        } catch (ApiException e) {
            checkExpectedError(expectedError, e);

            return null;
        }

    }

    public void testUpgradePAdESSignature() throws ApiException, Exception {

        File fileToUpgrade = new File("testfiles_serversignature/hola_signed.pdf");

        testUpgradePAdESSignature(fileToUpgrade);

    }

    protected void testUpgradePAdESSignature(File fileToUpgrade) throws Exception, ApiException {
        final String testName = "testUpgradePAdESSignature";
        final Integer expectedError = null;

        File upgradedFileName = new File("results/" + testName + "_" + fileToUpgrade.getName());

        internalTestUpgrade(PROFILE_PADES_PROPERTY, fileToUpgrade, null, upgradedFileName, testName, expectedError);
    }

    protected void internalTestUpgrade(final String perfilProperty, File fileToUpgrade,
            File documentDetached, File upgradedFileName, String testName, Integer expectedError)
            throws Exception, ApiException {

        System.out.println("============================ " + testName + " ============================");
        try {

            UtilitatsFirmaV2Api api = getApi();

            Properties prop = getConfigProperties();

            String profileCode = prop.getProperty(perfilProperty);

            if (profileCode == null || profileCode.trim().isEmpty()) {
                throw new Exception(
                        "La propietat " + perfilProperty + " no està definida al fitxer " + getConfigPropertiesFile());
            }

            /*
            UpgradeRequest upgradeRequest = new UpgradeRequest();
            
            upgradeRequest.setProfileCode(perfil);
            upgradeRequest.setDetachedDocument(documentDetached);
            upgradeRequest.setSignature(fileToUpgrade);
            */

            String languageUI = prop.getProperty("languageUI", "ca");

            final File detachedDocument = null;
            final File targetCertificate = null;

            
            UpgradeResponseMultipart upgradeResponse = api.upgradeSignature(languageUI, profileCode,  fileToUpgrade, 
                    detachedDocument, targetCertificate);

            System.out.println("============ SIGN MODE VALUES ============");
            for (SignModeConstants mode : SignModeConstants.values()) {
                System.out.println(mode.getValue() + " => " + mode.name());
            }

            System.out.println("==========================================");

            System.out.println(upgradeResponse.getUpgradedFileInfo().toString());

            File upgraded = upgradeResponse.getUpgradedFile();
            
            //System.out.println("Fitxer actualitzat: " + upgraded);
            if (upgraded != null) {
                
                
                System.out.println("Name: " + upgraded.getName());
                System.out.println("Mida: " + upgraded.length() + " bytes");
                
                
                upgradedFileName.delete(); // Eliminar el fitxer si ja existeix
                
                if (!upgraded.renameTo(upgradedFileName)) {
                    throw new Exception("No s'ha pogut renombrar el fitxer actualitzat a '" + upgradedFileName.getAbsolutePath() + "'");
                } else {
                    System.out.println("Fitxer actualitzat guardat en '" + upgradedFileName.getAbsolutePath() + "'");
                }

                
            }


            //return upgradeResponse;
            
       
            
            
            
            /*
            UpgradeResponse upgradeResponse = api.upgradeSignature(profileCode, fileToUpgrade, languageUI,
                    detachedDocument, targetCertificate);

            System.out.println("============ SIGN MODE VALUES ============");
            for (SignModeConstants mode : SignModeConstants.values()) {
                System.out.println(mode.getValue() + " => " + mode.name());
            }

            System.out.println("==========================================");

            System.out.println(upgradeResponse.getUpgradedFileInfo().toString());

            Document upgraded = upgradeResponse.getUpgradedFile();
            
            System.out.println("Fitxer actualitzat: " + upgraded);
            if (upgraded != null) {
                
                
                guardarFitxer(upgraded.getData(), upgradedFileName);

                
            }


            //return upgradeResponse;
            */

        } catch (ApiException e) {
            checkExpectedError(expectedError, e);
            //return null;
        }
    }

    
    public UtilitatsFirmaV2Api getApi() throws Exception {
        return getApi(getApiClient());
    }

    
    public UtilitatsFirmaV2Api getApi(ApiClientWithJsonSupport client) throws Exception {
        UtilitatsFirmaV2Api api = new UtilitatsFirmaV2Api(client);
        return api;
    }

    public class EstatFinalNoOK extends Exception {

        protected final Integer internalCode;

        protected final String errorStackTrace;

        public EstatFinalNoOK(Integer internalCode, String message) {
            this(internalCode, message, null);
        }

        public EstatFinalNoOK(Integer internalCode, String message, String errorStackTrace) {
            super(message);
            this.errorStackTrace = errorStackTrace;
            this.internalCode = internalCode;
        }

        public String getErrorStackTrace() {
            return errorStackTrace;
        }

        public Integer getInternalCode() {
            return internalCode;
        }

    }



 


    protected String getConfigPropertiesFile() {
        return "utilitatsfirma.properties";
    }

    public void testValidateSignatures() throws ApiException, Exception {

        SignatureRequestedInformation sri = new SignatureRequestedInformation();
        sri.setReturnValidationChecks(true);
        sri.setReturnCertificateInfo(true);
        sri.setReturnSignatureTypeFormatProfile(true);
        sri.setReturnTimeStampInfo(true);
        sri.setValidateCertificateRevocation(true);
        sri.setReturnCertificates(true);

        File[][] files = getFilesToValidate(getConfigProperties());

        for (int i = 0; i < files.length; i++) {

            // Per cada fitxer, fem una validació de la firma
            // i mostrem el resultat de la validació.
            File signatureDocument = files[i][0];

            System.out.println(" ======================= " + files[i][0].getName() + " ======================= ");

            File detachedDocument = null;
            if (files[i][1] == null) {
                detachedDocument = null;
            } else {
                detachedDocument = files[i][1];
            }

            ValidateSignatureResponse response = getApi().validateSignature(getLanguageUI(), sri, signatureDocument, 
                    detachedDocument);

            if (response != null && response.getValidationStatus() != null) {

                if (response.getValidationStatus().getStatus() != null) {
                    System.out.println("** Estat Validació: "
                            + ValidationStatusConstants.fromValue(response.getValidationStatus().getStatus()).name());
                }

                if (response.getValidationStatus().getStatus() != ValidationStatusConstants.SIGNATURE_ERROR
                        .getValue()) {

                    if (response.getSignMode() != null) {
                        System.out.println("** Mode de firma: " + response.getSignMode());
                    }

                    if (response.getSignatureDetailInfo() != null) {
                        Integer clasification = response.getSignatureDetailInfo().get(0).getCertificateInfo()
                                .getCertificateTypeMinetur();
                        if (clasification != null) {
                            System.out.println("** Tipus Certificat Minetur: "
                                    + CertificateTypeMineturConstants.fromValue(clasification).name());
                        }

                        String clasificationEidas = response.getSignatureDetailInfo().get(0).getCertificateInfo()
                                .getCertificateTypeEidas();
                        if (clasificationEidas != null) {
                            System.out.println("** Tipus Certificat EIDAS: "
                                    + CertificateTypeEidasConstants.fromValue(clasificationEidas).name());
                        }

                    }

                }
            }
            System.out.println("---------------");
            System.out.println(response);
        }

    }

    protected File[][] getFilesToValidate(Properties prop) throws Exception {

        String files = prop.getProperty("validatefiles");
        String[] parts = files.split(",");
        File[][] filesToSign = new File[parts.length][];

        for (int i = 0; i < parts.length; i++) {

            String nom = prop.getProperty("validatefile." + parts[i] + ".name");
            System.out.println("*** FILE[" + parts[i] + "]");
            System.out.println("    Name = " + nom);
            String mime = prop.getProperty("file." + parts[i] + ".mime");

            System.out.println("    Mime: ]" + mime + "[");

            File fileToSign = new File(nom); //, mime);
            //System.out.println("    Mida: " + fileToSign.getData().length + " bytes");

            filesToSign[i] = new File[2];
            filesToSign[i][0] = fileToSign;

            String detached = prop.getProperty("file." + parts[i] + ".detached");

            if (detached == null) {
                filesToSign[i][1] = null;
            } else {
                //Document detachedDoc = llegirFitxer(detached, "application/octet-stream");
                filesToSign[i][1] = new File(detached);
            }

        }

        return filesToSign;
    }
    
    
    

    public static final String PROFILE_PADES_PROPERTY = "PROFILE_PADES";

    public static final String PROFILE_XADES_PROPERTY = "PROFILE_XADES";

    public static final String PROFILE_CADES_PROPERTY = "PROFILE_CADES";

    public static final String PROFILE_MIX_PADES_XADES_CADES = "PROFILE_MIX_PADES_XADES_CADES";



    public void testTipusDocumentalListWithNotValidAppUser() throws ApiException, Exception {

        final Integer expectedError = 401;
        ApiClientWithJsonSupport apiClient = getApiClient();
        apiClient.setPassword("holacaracola");
        internalTestTipusDocumentalList(expectedError, "callTipusDocumentalListWithNotValidAppUserTest", apiClient);
        System.out.println("Test OK");
    }

    public void testTipusDocumentalList() throws ApiException, Exception {

        final Integer expectedError = null;

        ApiClientWithJsonSupport apiClient = getApiClient();

        internalTestTipusDocumentalList(expectedError, "callTipusDocumentalListTest", apiClient);
    }

    public void testPerfilsDeFirmaList() throws ApiException, Exception {

        Integer expectedError = null;

        internalTestPerfilsDeFirmaList(expectedError, "callPerfilsDeFirmaListTest");
    }

    public void testAvailableLanguages() throws ApiException, Exception {

        Integer expectedError = null;

        internalTestAvailableLanguages(expectedError, "callAvailable LanguagesTest");
    }

    protected Set<KeyValue> internalTestAvailableLanguages(Integer expectedError, String testName)
            throws ApiException, Exception {
        System.out.println("============================ " + testName + " ============================");
        try {

            String languageUI = getLanguageUI(getConfigProperties());

            Set<KeyValue> response = getApi().getLanguages(languageUI);
            if (expectedError != null) {
                log.error(testName + ": S'espera un error " + expectedError + " i la cridada ha funcionat.");
            }
            System.out.println(response.toString());
            return response;
        } catch (ApiException e) {
            checkExpectedError(expectedError, e);
            return null;
        }

    }

    protected Set<Profile> internalTestPerfilsDeFirmaList(Integer expectedError, String testName)
            throws ApiException, Exception {
        System.out.println("============================ " + testName + " ============================");
        try {
            String languageUI = getLanguageUI(getConfigProperties());

            Set<Profile> response = getApi().getProfiles(languageUI);;
            if (expectedError != null) {
                log.error(testName + ": S'espera un error " + expectedError + " i la cridada ha funcionat.");
            }
            System.out.println(response.toString());
            return response;
        } catch (ApiException e) {
            checkExpectedError(expectedError, e);
            return null;
        }

    }

    protected Set<DocumentaryType> internalTestTipusDocumentalList(Integer expectedError, String testName,
            ApiClientWithJsonSupport apiClient) throws ApiException, Exception {
        System.out.println("============================ " + testName + " ============================");

        try {

            String languageUI = getLanguageUI(getConfigProperties());

            //ApiClient apiClient = getApiClient();

            Set<DocumentaryType> response = getApi(apiClient).getDocumentaryTypes(languageUI);
            if (expectedError != null) {
                throw new Exception(
                        testName + ": S'espera un error " + expectedError + " però la cridada ha funcionat.");
            }

            System.out.println(response.toString());
            return response;
        } catch (ApiException e) {
            checkExpectedError(expectedError, e);
            return null;
        }

    }
    
    
    protected File getResultsDirectory() {
        File res = new File("results");
        res.mkdirs();
        return res;
    }
    

    protected List<FileToSign> getPdfFilesToSign(Properties prop, long tipusDocumentalID) throws Exception {

        List<File> documentsToSign = getPdfDocumentsToSign(prop);
        List<FileToSign> filesToSign = new ArrayList<>(documentsToSign.size());
        int count = 0;
        for(File file: documentsToSign) {
            FileInfoSignatureV2 fileInfoSignature = new FileInfoSignatureV2();

            String signID = "Firma_" + count;
            
            fileInfoSignature.setSignID(signID);
            String name = file.getName();
            fileInfoSignature.setName(name);
            String reason = "Per aprovar pressuposts - " + file.getName();
            fileInfoSignature.setReason(reason);
            String location = "Palma";
            fileInfoSignature.setLocation(location);

            int signNumber = 1;
            fileInfoSignature.setSignNumber(signNumber);
            String languageSign = getLanguageUI(prop);
            fileInfoSignature.setLanguageSign(languageSign);

            fileInfoSignature.setDocumentType(tipusDocumentalID);

            
            FileToSign fts = new FileToSign();
            fts.setFileInfoSignatureV2(fileInfoSignature);
            fts.setFileToSign(file);
            
            
            filesToSign.add(fts); 
            count++;
        }

        return filesToSign;
    }
    
    
    protected List<File> getPdfDocumentsToSign(Properties prop) throws IOException {
        List<File> documentsToSign;
        String files = prop.getProperty("pdffiles");
        String[] parts = files.split(",");
         documentsToSign = new ArrayList<>(parts.length);

        for (int i = 0; i < parts.length; i++) {

            String nom = prop.getProperty("pdffile." + parts[i] + ".name");
            System.out.println("*** FILE[" + parts[i] + "]");
            System.out.println("    Name = " + nom);
            String mime = prop.getProperty("pdffile." + parts[i] + ".mime");

            System.out.println("    Mime: ]" + mime + "[");

            File f = new File(nom);
            documentsToSign.add(f);
            System.out.println("    Mida: " + f.length() + " bytes");
        }
        return documentsToSign;
    }

   


    private Properties properties = null;

    protected ApiClientWithJsonSupport getApiClient() throws Exception {

        Properties prop = getConfigProperties();
        String languageUI = getLanguageUI(prop);

        String basePath = getRequiredProperty(prop, "basePath");
        log.debug("BasePath: " + basePath);
        String username = getRequiredProperty(prop, "username");
        log.debug("Username: " + username);
        String password = getRequiredProperty(prop, "password");

        ApiClientWithJsonSupport apiClient = getApiClient(basePath, username, password, languageUI);

        return apiClient;
    }

    protected ApiClientWithJsonSupport getApiClient(String basePath, String username, String password, String languageUI) {
        ApiClientWithJsonSupport client = new ApiClientWithJsonSupport();
        client.setBasePath(basePath);
        client.setUsername(username);
        client.setPassword(password);

        client.setDebugging(true);

        client.addDefaultHeader("Accept-Language", languageUI);
        return client;
    }

    protected String getLanguageUI(Properties prop) throws Exception {
        return getRequiredProperty(prop, "languageUI");
    }

    protected String getLanguageUI() throws Exception {
        Properties prop = getConfigProperties();
        return getRequiredProperty(prop, "languageUI");
    }

    protected String getRequiredProperty(Properties prop, String propName) throws Exception {
        String p = prop.getProperty(propName);
        if (p == null) {
            throw new Exception("No s'ha trobat la propietat " + propName + " al fitxer de configuració "
                    + getConfigPropertiesFile());
        }
        return p;
    }

    protected boolean processApiException(ApiException e, final String testName, boolean printLogs) {

        if (printLogs) {
            //log.error("Stack trace:", e);
            log.error(" -------------------------------------------------------");
            log.error("Error durant la realització del test: " + testName);
            log.error("    - Code: " + e.getCode() + " (" + Status.fromStatusCode(e.getCode()).name() + ")");
        }

        int status = e.getCode();
        if (status == 400 || status == 401 || status == 403 || status == 500) {

            try {
                ObjectMapper objectMapper = es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.services.Configuration
                        .getDefaultApiClient().getJSON().getContext(null);
                RestExceptionInfo rei = objectMapper.readValue(e.getMessage(), RestExceptionInfo.class);
                if (printLogs) {
                    log.error("    - RestExceptionInfo:" + "\n" + "          + errorCode: " + rei.getErrorCode() + "\n"
                            + "          + errorMessage: " + rei.getErrorMessage() + "\n" + "          + stackTrace: "
                            + rei.getStackTrace() + "\n" + "          + stackTraceCause: " + rei.getStackTraceCause()
                            + "\n" + "          + field: " + rei.getField());
                }
            } catch (Exception e1) {
                //e1.printStackTrace();
                // No es un objecte RestExceptionInfo
                if (printLogs) {
                    log.error(
                            "    - Message: Error no controlat realitzant: " + testName + ". Error: " + e.getMessage());
                    log.error("\n"
                            + "    ---------------------------------- IMPORTANT -------------------------------\n"
                            + "    El body del missatge HTTP hauria de contenir un objecte RestExceptionInfo\n"
                            + "    representat en format JSON però en el seu lloc conté:\n" + e.getMessage() + "\n"
                            + "    ----------------------------------------------------------------------------\n");
                }
                return false;
            }
        } else {
            if (printLogs) {
                log.error("    - Message: Error no controlat realitzant: " + testName + ". Error: " + e.getMessage());
            }
        }
        return true;
    }

    protected void checkExpectedError(Integer expectedError, ApiException e) throws ApiException {
        if (expectedError == null || e.getCode() != expectedError) {
            throw e;
        }
        // Validar que l'excepció es correcta

        if (!processApiException(e, "Check if ApiException contains RestExceptionInfo", false)) {

            log.error("    ----------------- IMPORTANT ----------------\n"
                    + "    El body del missatge HTTP hauria de contenir\n"
                    + "    un objecte RestExceptionInfo representat en\n"
                    + "    format JSON però en el seu lloc conté:\n" + e.getMessage() + "\n"
                    + "    ---------------------------------------------");
        }

    }

    protected Properties getConfigProperties() throws Exception {
        if (properties == null) {

            File f = new File(getConfigPropertiesFile());
            if (!f.exists()) {
                throw new Exception("No s'ha trobat el fitxer de configuració: " + f.getAbsolutePath());
            }

            Properties prop = new Properties();
            prop.load(new FileInputStream(f));
            properties = prop;
        }
        return properties;
    }

    /*
    public static Document llegirFitxer(String fileName, String mime) throws IOException {

        byte[] data = readDataFromFile(fileName);

        Document asf = new Document();
        asf.setName(new File(fileName).getName());
        asf.setMime(mime);
        asf.setData(data);

        return asf;
    }
    */

    protected void guardarFitxer(byte[] data, File file) throws FileNotFoundException, IOException {

        file.getParentFile().mkdirs(); // Assegurar que el directori existeix

        FileOutputStream fos = new FileOutputStream(file);
        fos.write(data);
        fos.flush();
        fos.close();

        System.out.println("Guardat " + file.getAbsolutePath());
    }

    public static byte[] readDataFromFile(String fileName) throws FileNotFoundException, IOException {
        InputStream is = new FileInputStream(new File(fileName));
        ByteArrayOutputStream fos = new ByteArrayOutputStream();
        copyFileToOutputStream(is, fos);
        byte[] data = fos.toByteArray();
        return data;
    }

    public static void copyFileToOutputStream(InputStream input, OutputStream output) throws IOException {
        byte[] buffer = new byte[4096];
        int n = 0;
        while (-1 != (n = input.read(buffer))) {
            output.write(buffer, 0, n);
        }
    }


}
