-- create index suf_estadistica_pk_i on suf_estadistica (estadisticaid);
-- create index suf_idioma_pk_i on suf_idioma (idiomaid);
create index suf_perfilsua_uaperfil_fk_i on suf_perfilsperusrapp (usuariaplicacioperfilid);
create index suf_plugin_nomid_fk_i on suf_plugin (nomid);
-- create index suf_traduccio_pk_i on suf_traduccio (traduccioid);
-- create index suf_usuariaplicacioconfig_pk_i on suf_usuariaplicacioconfig (usuariaplicacioconfigid);
-- create index pfi_usuariaplicacioperfil_pk_i on suf_usuariaplicacioperfil (usuariaplicacioperfilid);
create index suf_perfilapp_usrconf2id_fk_i on suf_usuariaplicacioperfil (usrappconfiguracio2id);
create index suf_perfilapp_usrconf4id_fk_i on suf_usuariaplicacioperfil (usrappconfiguracio4id);
-- create index suf_validacio_pk_i on suf_validacio (validacioid);
create index suf_validacio_detachedid_fk_i on suf_validacio (detachedid);
