/*
 * OpenAPI
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Tipus de Firma. Valors possibles:     - “PAdES” (Constant SIGN_TYPE_PADES)     - “XAdES” (Constant SIGN_TYPE_XADES)     - “CAdES” (Constant SIGN_TYPE_CADES)     - “FacturaE” (Constant SIGN_TYPE_FACTURAE)     - “OOXML” (Constant SIGN_TYPE_OOXML)     - “ODF” (Constant SIGN_TYPE_ODF)     - “SMIME” (Constant SIGN_TYPE_SMIME)     - “CAdES-ASiC-S” (Constant SIGN_TYPE_CADES_ASIC_S)     - “XAdES-ASiC-S” (Constant SIGN_TYPE_XADES_ASIC_S)     - “PKCS#1” (Constant SIGN_TYPE_PKCS1)
 */
public enum SignTypeConstants {
  
  /**
   *  
   */
  SIGN_TYPE_PADES("PAdES"),
  
  /**
   *  
   */
  SIGN_TYPE_XADES("XAdES"),
  
  /**
   *  
   */
  SIGN_TYPE_CADES("CAdES"),
  
  /**
   *  
   */
  SIGN_TYPE_FACTURAE("FacturaE"),
  
  /**
   *  
   */
  SIGN_TYPE_OOXML("OOXML"),
  
  /**
   *  
   */
  SIGN_TYPE_ODF("ODF"),
  
  /**
   *  
   */
  SIGN_TYPE_SMIME("SMIME"),
  
  /**
   *  
   */
  SIGN_TYPE_CADESASICS("CAdES-ASiC-S"),
  
  /**
   *  
   */
  SIGN_TYPE_XADESASICS("XAdES-ASiC-S"),
  
  /**
   *  
   */
  SIGN_TYPE_PKCS("PKCS#1");

  private String value;

  SignTypeConstants(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static SignTypeConstants fromValue(String value) {
    for (SignTypeConstants b : SignTypeConstants.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

