/*
 * OpenAPI
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Posició de la Taula de firmes:      • 0: Sense taula de firmes      • 1: Taula de firmes en la 1a pàgina      • -1: Darrera pàgina
 */
public enum SignaturesTableLocationConstants {
  
  /**
   * Sense taula de firmes
   */
  SIGNATURES_TABLE_LOCATION_WITHOUT(0),
  
  /**
   * Taula de firmes en la 1a pàgina
   */
  SIGNATURES_TABLE_LOCATION_FIRSTPAGE(1),
  
  /**
   * Darrera pàgina
   */
  SIGNATURES_TABLE_LOCATION_LASTPAGE(-1);

  private Integer value;

  SignaturesTableLocationConstants(Integer value) {
    this.value = value;
  }

  @JsonValue
  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static SignaturesTableLocationConstants fromValue(Integer value) {
    for (SignaturesTableLocationConstants b : SignaturesTableLocationConstants.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

