/*
 * OpenAPI
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Valors:      • STATUS_INITIALIZING: Codi d&#39;estat d&#39;una petició de firma que indica un que s&#39;esta inicialitzant.     • STATUS_IN_PROGRESS: Codi d&#39;estat d&#39;una petició de firma que indica un que esta en procés.     • STATUS_FINAL_OK: Codi d&#39;estat d&#39;una petició de firma que indica que ha finalitzat correctament     • STATUS_FINAL_ERROR: Codi d&#39;estat d&#39;una petició de firma que indica que ha finalitzat amb errors     • STATUS_CANCELLED: Codi d&#39;estat d&#39;una petició de firma que indica que ha sigut cancelada 
 */
public enum StatusConstants {
  
  /**
   * Codi d&#39;estat d&#39;una petició de firma que indica un que s&#39;esta inicialitzant.
   */
  STATUS_INITIALIZING(0),
  
  /**
   * Codi d&#39;estat d&#39;una petició de firma que indica un que esta en procés.
   */
  STATUS_IN_PROGRESS(1),
  
  /**
   * Codi d&#39;estat d&#39;una petició de firma que indica que ha finalitzat correctament
   */
  STATUS_FINAL_OK(2),
  
  /**
   * Codi d&#39;estat d&#39;una petició de firma que indica que ha finalitzat amb errors
   */
  STATUS_FINAL_ERROR(-1),
  
  /**
   * Codi d&#39;estat d&#39;una petició de firma que indica que ha sigut cancelada
   */
  STATUS_CANCELLED(-2);

  private Integer value;

  StatusConstants(Integer value) {
    this.value = value;
  }

  @JsonValue
  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static StatusConstants fromValue(Integer value) {
    for (StatusConstants b : StatusConstants.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

