/*
 * Utilitats Firma Swagger v2
 * API Interna d'Utilitats Firma V2 que ofereix serveis de firma en servidor i validació de firmes.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: governdigital.firma@ibdigital.caib.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.KeyValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Informació no criptogràfica associada a una firma.
 */
@JsonPropertyOrder({
  NonCryptographicInformation.JSON_PROPERTY_NAME,
  NonCryptographicInformation.JSON_PROPERTY_SURNAME1,
  NonCryptographicInformation.JSON_PROPERTY_SURNAME2,
  NonCryptographicInformation.JSON_PROPERTY_ADMINISTRATION_I_D,
  NonCryptographicInformation.JSON_PROPERTY_NON_CRYPTOGRAPHIC_SYSTEM_NAME,
  NonCryptographicInformation.JSON_PROPERTY_NON_CRYPTOGRAPHIC_SYSTEM_CODE,
  NonCryptographicInformation.JSON_PROPERTY_NON_CRYPTOGRAPHIC_SIGNATURE_IDENTIFIER,
  NonCryptographicInformation.JSON_PROPERTY_DATE_OF_SIGNATURE,
  NonCryptographicInformation.JSON_PROPERTY_URL_TO_WEB_INFO,
  NonCryptographicInformation.JSON_PROPERTY_URL_TO_DOWNLOAD_FILE,
  NonCryptographicInformation.JSON_PROPERTY_ADDITIONAL_INFORMATION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class NonCryptographicInformation {
  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_SURNAME1 = "surname1";
  @javax.annotation.Nullable
  private String surname1;

  public static final String JSON_PROPERTY_SURNAME2 = "surname2";
  @javax.annotation.Nullable
  private String surname2;

  public static final String JSON_PROPERTY_ADMINISTRATION_I_D = "administrationID";
  @javax.annotation.Nullable
  private String administrationID;

  public static final String JSON_PROPERTY_NON_CRYPTOGRAPHIC_SYSTEM_NAME = "nonCryptographicSystemName";
  @javax.annotation.Nullable
  private String nonCryptographicSystemName;

  public static final String JSON_PROPERTY_NON_CRYPTOGRAPHIC_SYSTEM_CODE = "nonCryptographicSystemCode";
  @javax.annotation.Nullable
  private String nonCryptographicSystemCode;

  public static final String JSON_PROPERTY_NON_CRYPTOGRAPHIC_SIGNATURE_IDENTIFIER = "nonCryptographicSignatureIdentifier";
  @javax.annotation.Nullable
  private String nonCryptographicSignatureIdentifier;

  public static final String JSON_PROPERTY_DATE_OF_SIGNATURE = "dateOfSignature";
  @javax.annotation.Nullable
  private OffsetDateTime dateOfSignature;

  public static final String JSON_PROPERTY_URL_TO_WEB_INFO = "urlToWebInfo";
  @javax.annotation.Nullable
  private String urlToWebInfo;

  public static final String JSON_PROPERTY_URL_TO_DOWNLOAD_FILE = "urlToDownloadFile";
  @javax.annotation.Nullable
  private String urlToDownloadFile;

  public static final String JSON_PROPERTY_ADDITIONAL_INFORMATION = "additionalInformation";
  @javax.annotation.Nullable
  private List<KeyValue> additionalInformation = new ArrayList<>();

  public NonCryptographicInformation() {
  }

  public NonCryptographicInformation name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }

  public NonCryptographicInformation surname1(@javax.annotation.Nullable String surname1) {
    
    this.surname1 = surname1;
    return this;
  }

  /**
   * Get surname1
   * @return surname1
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SURNAME1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSurname1() {
    return surname1;
  }


  @JsonProperty(JSON_PROPERTY_SURNAME1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSurname1(@javax.annotation.Nullable String surname1) {
    this.surname1 = surname1;
  }

  public NonCryptographicInformation surname2(@javax.annotation.Nullable String surname2) {
    
    this.surname2 = surname2;
    return this;
  }

  /**
   * Get surname2
   * @return surname2
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SURNAME2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSurname2() {
    return surname2;
  }


  @JsonProperty(JSON_PROPERTY_SURNAME2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSurname2(@javax.annotation.Nullable String surname2) {
    this.surname2 = surname2;
  }

  public NonCryptographicInformation administrationID(@javax.annotation.Nullable String administrationID) {
    
    this.administrationID = administrationID;
    return this;
  }

  /**
   * Get administrationID
   * @return administrationID
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADMINISTRATION_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAdministrationID() {
    return administrationID;
  }


  @JsonProperty(JSON_PROPERTY_ADMINISTRATION_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdministrationID(@javax.annotation.Nullable String administrationID) {
    this.administrationID = administrationID;
  }

  public NonCryptographicInformation nonCryptographicSystemName(@javax.annotation.Nullable String nonCryptographicSystemName) {
    
    this.nonCryptographicSystemName = nonCryptographicSystemName;
    return this;
  }

  /**
   * Get nonCryptographicSystemName
   * @return nonCryptographicSystemName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NON_CRYPTOGRAPHIC_SYSTEM_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNonCryptographicSystemName() {
    return nonCryptographicSystemName;
  }


  @JsonProperty(JSON_PROPERTY_NON_CRYPTOGRAPHIC_SYSTEM_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNonCryptographicSystemName(@javax.annotation.Nullable String nonCryptographicSystemName) {
    this.nonCryptographicSystemName = nonCryptographicSystemName;
  }

  public NonCryptographicInformation nonCryptographicSystemCode(@javax.annotation.Nullable String nonCryptographicSystemCode) {
    
    this.nonCryptographicSystemCode = nonCryptographicSystemCode;
    return this;
  }

  /**
   * Get nonCryptographicSystemCode
   * @return nonCryptographicSystemCode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NON_CRYPTOGRAPHIC_SYSTEM_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNonCryptographicSystemCode() {
    return nonCryptographicSystemCode;
  }


  @JsonProperty(JSON_PROPERTY_NON_CRYPTOGRAPHIC_SYSTEM_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNonCryptographicSystemCode(@javax.annotation.Nullable String nonCryptographicSystemCode) {
    this.nonCryptographicSystemCode = nonCryptographicSystemCode;
  }

  public NonCryptographicInformation nonCryptographicSignatureIdentifier(@javax.annotation.Nullable String nonCryptographicSignatureIdentifier) {
    
    this.nonCryptographicSignatureIdentifier = nonCryptographicSignatureIdentifier;
    return this;
  }

  /**
   * Get nonCryptographicSignatureIdentifier
   * @return nonCryptographicSignatureIdentifier
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NON_CRYPTOGRAPHIC_SIGNATURE_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNonCryptographicSignatureIdentifier() {
    return nonCryptographicSignatureIdentifier;
  }


  @JsonProperty(JSON_PROPERTY_NON_CRYPTOGRAPHIC_SIGNATURE_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNonCryptographicSignatureIdentifier(@javax.annotation.Nullable String nonCryptographicSignatureIdentifier) {
    this.nonCryptographicSignatureIdentifier = nonCryptographicSignatureIdentifier;
  }

  public NonCryptographicInformation dateOfSignature(@javax.annotation.Nullable OffsetDateTime dateOfSignature) {
    
    this.dateOfSignature = dateOfSignature;
    return this;
  }

  /**
   * Get dateOfSignature
   * @return dateOfSignature
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATE_OF_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDateOfSignature() {
    return dateOfSignature;
  }


  @JsonProperty(JSON_PROPERTY_DATE_OF_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateOfSignature(@javax.annotation.Nullable OffsetDateTime dateOfSignature) {
    this.dateOfSignature = dateOfSignature;
  }

  public NonCryptographicInformation urlToWebInfo(@javax.annotation.Nullable String urlToWebInfo) {
    
    this.urlToWebInfo = urlToWebInfo;
    return this;
  }

  /**
   * Get urlToWebInfo
   * @return urlToWebInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL_TO_WEB_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrlToWebInfo() {
    return urlToWebInfo;
  }


  @JsonProperty(JSON_PROPERTY_URL_TO_WEB_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrlToWebInfo(@javax.annotation.Nullable String urlToWebInfo) {
    this.urlToWebInfo = urlToWebInfo;
  }

  public NonCryptographicInformation urlToDownloadFile(@javax.annotation.Nullable String urlToDownloadFile) {
    
    this.urlToDownloadFile = urlToDownloadFile;
    return this;
  }

  /**
   * Get urlToDownloadFile
   * @return urlToDownloadFile
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL_TO_DOWNLOAD_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrlToDownloadFile() {
    return urlToDownloadFile;
  }


  @JsonProperty(JSON_PROPERTY_URL_TO_DOWNLOAD_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrlToDownloadFile(@javax.annotation.Nullable String urlToDownloadFile) {
    this.urlToDownloadFile = urlToDownloadFile;
  }

  public NonCryptographicInformation additionalInformation(@javax.annotation.Nullable List<KeyValue> additionalInformation) {
    
    this.additionalInformation = additionalInformation;
    return this;
  }

  public NonCryptographicInformation addAdditionalInformationItem(KeyValue additionalInformationItem) {
    if (this.additionalInformation == null) {
      this.additionalInformation = new ArrayList<>();
    }
    this.additionalInformation.add(additionalInformationItem);
    return this;
  }

  /**
   * Get additionalInformation
   * @return additionalInformation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<KeyValue> getAdditionalInformation() {
    return additionalInformation;
  }


  @JsonProperty(JSON_PROPERTY_ADDITIONAL_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdditionalInformation(@javax.annotation.Nullable List<KeyValue> additionalInformation) {
    this.additionalInformation = additionalInformation;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NonCryptographicInformation nonCryptographicInformation = (NonCryptographicInformation) o;
    return Objects.equals(this.name, nonCryptographicInformation.name) &&
        Objects.equals(this.surname1, nonCryptographicInformation.surname1) &&
        Objects.equals(this.surname2, nonCryptographicInformation.surname2) &&
        Objects.equals(this.administrationID, nonCryptographicInformation.administrationID) &&
        Objects.equals(this.nonCryptographicSystemName, nonCryptographicInformation.nonCryptographicSystemName) &&
        Objects.equals(this.nonCryptographicSystemCode, nonCryptographicInformation.nonCryptographicSystemCode) &&
        Objects.equals(this.nonCryptographicSignatureIdentifier, nonCryptographicInformation.nonCryptographicSignatureIdentifier) &&
        Objects.equals(this.dateOfSignature, nonCryptographicInformation.dateOfSignature) &&
        Objects.equals(this.urlToWebInfo, nonCryptographicInformation.urlToWebInfo) &&
        Objects.equals(this.urlToDownloadFile, nonCryptographicInformation.urlToDownloadFile) &&
        Objects.equals(this.additionalInformation, nonCryptographicInformation.additionalInformation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, surname1, surname2, administrationID, nonCryptographicSystemName, nonCryptographicSystemCode, nonCryptographicSignatureIdentifier, dateOfSignature, urlToWebInfo, urlToDownloadFile, additionalInformation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NonCryptographicInformation {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    surname1: ").append(toIndentedString(surname1)).append("\n");
    sb.append("    surname2: ").append(toIndentedString(surname2)).append("\n");
    sb.append("    administrationID: ").append(toIndentedString(administrationID)).append("\n");
    sb.append("    nonCryptographicSystemName: ").append(toIndentedString(nonCryptographicSystemName)).append("\n");
    sb.append("    nonCryptographicSystemCode: ").append(toIndentedString(nonCryptographicSystemCode)).append("\n");
    sb.append("    nonCryptographicSignatureIdentifier: ").append(toIndentedString(nonCryptographicSignatureIdentifier)).append("\n");
    sb.append("    dateOfSignature: ").append(toIndentedString(dateOfSignature)).append("\n");
    sb.append("    urlToWebInfo: ").append(toIndentedString(urlToWebInfo)).append("\n");
    sb.append("    urlToDownloadFile: ").append(toIndentedString(urlToDownloadFile)).append("\n");
    sb.append("    additionalInformation: ").append(toIndentedString(additionalInformation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

