/*
 * Utilitats Firma Swagger v2
 * API Interna d'Utilitats Firma V2 que ofereix serveis de firma en servidor i validació de firmes.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: governdigital.firma@ibdigital.caib.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.CommonInfo;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.FileInfoSignatureV2;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Petició de firma en servidor
 */
@JsonPropertyOrder({
  SignDocumentRequestV2.JSON_PROPERTY_COMMON_INFO,
  SignDocumentRequestV2.JSON_PROPERTY_FILE_INFO_SIGNATURE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class SignDocumentRequestV2 {
  public static final String JSON_PROPERTY_COMMON_INFO = "commonInfo";
  @javax.annotation.Nonnull
  private CommonInfo commonInfo;

  public static final String JSON_PROPERTY_FILE_INFO_SIGNATURE = "fileInfoSignature";
  @javax.annotation.Nonnull
  private FileInfoSignatureV2 fileInfoSignature;

  public SignDocumentRequestV2() {
  }

  public SignDocumentRequestV2 commonInfo(@javax.annotation.Nonnull CommonInfo commonInfo) {
    
    this.commonInfo = commonInfo;
    return this;
  }

  /**
   * Get commonInfo
   * @return commonInfo
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COMMON_INFO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public CommonInfo getCommonInfo() {
    return commonInfo;
  }


  @JsonProperty(JSON_PROPERTY_COMMON_INFO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCommonInfo(@javax.annotation.Nonnull CommonInfo commonInfo) {
    this.commonInfo = commonInfo;
  }

  public SignDocumentRequestV2 fileInfoSignature(@javax.annotation.Nonnull FileInfoSignatureV2 fileInfoSignature) {
    
    this.fileInfoSignature = fileInfoSignature;
    return this;
  }

  /**
   * Get fileInfoSignature
   * @return fileInfoSignature
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FILE_INFO_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public FileInfoSignatureV2 getFileInfoSignature() {
    return fileInfoSignature;
  }


  @JsonProperty(JSON_PROPERTY_FILE_INFO_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFileInfoSignature(@javax.annotation.Nonnull FileInfoSignatureV2 fileInfoSignature) {
    this.fileInfoSignature = fileInfoSignature;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignDocumentRequestV2 signDocumentRequestV2 = (SignDocumentRequestV2) o;
    return Objects.equals(this.commonInfo, signDocumentRequestV2.commonInfo) &&
        Objects.equals(this.fileInfoSignature, signDocumentRequestV2.fileInfoSignature);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commonInfo, fileInfoSignature);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignDocumentRequestV2 {\n");
    sb.append("    commonInfo: ").append(toIndentedString(commonInfo)).append("\n");
    sb.append("    fileInfoSignature: ").append(toIndentedString(fileInfoSignature)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

