/*
 * Utilitats Firma Swagger v2
 * API Interna d'Utilitats Firma V2 que ofereix serveis de firma en servidor i validació de firmes.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: governdigital.firma@ibdigital.caib.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.SignDocumentRequestV2;
import java.io.File;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Petición de firma en servidor en formato multipart, con información de la firma y el documento a firmar
 */
@JsonPropertyOrder({
  SignDocumentRequestMultipart.JSON_PROPERTY_SIGN_DOCUMENT_REQUEST,
  SignDocumentRequestMultipart.JSON_PROPERTY_FILE_TO_SIGN,
  SignDocumentRequestMultipart.JSON_PROPERTY_PREVIOUS_SIGNATURE_DETACHED_FILE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class SignDocumentRequestMultipart {
  public static final String JSON_PROPERTY_SIGN_DOCUMENT_REQUEST = "signDocumentRequest";
  @javax.annotation.Nullable
  private SignDocumentRequestV2 signDocumentRequest;

  public static final String JSON_PROPERTY_FILE_TO_SIGN = "fileToSign";
  @javax.annotation.Nullable
  private File fileToSign;

  public static final String JSON_PROPERTY_PREVIOUS_SIGNATURE_DETACHED_FILE = "previousSignatureDetachedFile";
  @javax.annotation.Nullable
  private File previousSignatureDetachedFile;

  public SignDocumentRequestMultipart() {
  }

  public SignDocumentRequestMultipart signDocumentRequest(@javax.annotation.Nullable SignDocumentRequestV2 signDocumentRequest) {
    
    this.signDocumentRequest = signDocumentRequest;
    return this;
  }

  /**
   * Get signDocumentRequest
   * @return signDocumentRequest
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGN_DOCUMENT_REQUEST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SignDocumentRequestV2 getSignDocumentRequest() {
    return signDocumentRequest;
  }


  @JsonProperty(JSON_PROPERTY_SIGN_DOCUMENT_REQUEST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignDocumentRequest(@javax.annotation.Nullable SignDocumentRequestV2 signDocumentRequest) {
    this.signDocumentRequest = signDocumentRequest;
  }

  public SignDocumentRequestMultipart fileToSign(@javax.annotation.Nullable File fileToSign) {
    
    this.fileToSign = fileToSign;
    return this;
  }

  /**
   * Get fileToSign
   * @return fileToSign
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILE_TO_SIGN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public File getFileToSign() {
    return fileToSign;
  }


  @JsonProperty(JSON_PROPERTY_FILE_TO_SIGN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFileToSign(@javax.annotation.Nullable File fileToSign) {
    this.fileToSign = fileToSign;
  }

  public SignDocumentRequestMultipart previousSignatureDetachedFile(@javax.annotation.Nullable File previousSignatureDetachedFile) {
    
    this.previousSignatureDetachedFile = previousSignatureDetachedFile;
    return this;
  }

  /**
   * Get previousSignatureDetachedFile
   * @return previousSignatureDetachedFile
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PREVIOUS_SIGNATURE_DETACHED_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public File getPreviousSignatureDetachedFile() {
    return previousSignatureDetachedFile;
  }


  @JsonProperty(JSON_PROPERTY_PREVIOUS_SIGNATURE_DETACHED_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreviousSignatureDetachedFile(@javax.annotation.Nullable File previousSignatureDetachedFile) {
    this.previousSignatureDetachedFile = previousSignatureDetachedFile;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignDocumentRequestMultipart signDocumentRequestMultipart = (SignDocumentRequestMultipart) o;
    return Objects.equals(this.signDocumentRequest, signDocumentRequestMultipart.signDocumentRequest) &&
        Objects.equals(this.fileToSign, signDocumentRequestMultipart.fileToSign) &&
        Objects.equals(this.previousSignatureDetachedFile, signDocumentRequestMultipart.previousSignatureDetachedFile);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signDocumentRequest, fileToSign, previousSignatureDetachedFile);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignDocumentRequestMultipart {\n");
    sb.append("    signDocumentRequest: ").append(toIndentedString(signDocumentRequest)).append("\n");
    sb.append("    fileToSign: ").append(toIndentedString(fileToSign)).append("\n");
    sb.append("    previousSignatureDetachedFile: ").append(toIndentedString(previousSignatureDetachedFile)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

