/*
 * Utilitats Firma Swagger v2
 * API Interna d'Utilitats Firma V2 que ofereix serveis de firma en servidor i validació de firmes.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: governdigital.firma@ibdigital.caib.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.SignAlgorithmEnum;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.SignModeEnum;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.SignOperationEnum;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.SignTypeEnum;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SignatureTypeInfo
 */
@JsonPropertyOrder({
  SignatureTypeInfo.JSON_PROPERTY_PROFILE_CODE,
  SignatureTypeInfo.JSON_PROPERTY_SIGN_OPERATION,
  SignatureTypeInfo.JSON_PROPERTY_SIGN_TYPE,
  SignatureTypeInfo.JSON_PROPERTY_SIGN_ALGORITHM,
  SignatureTypeInfo.JSON_PROPERTY_SIGN_MODE,
  SignatureTypeInfo.JSON_PROPERTY_TIME_STAMP_INCLUDED,
  SignatureTypeInfo.JSON_PROPERTY_POLICY_INCLUDED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class SignatureTypeInfo {
  public static final String JSON_PROPERTY_PROFILE_CODE = "profileCode";
  @javax.annotation.Nonnull
  private String profileCode;

  public static final String JSON_PROPERTY_SIGN_OPERATION = "signOperation";
  @javax.annotation.Nonnull
  private SignOperationEnum signOperation;

  public static final String JSON_PROPERTY_SIGN_TYPE = "signType";
  @javax.annotation.Nonnull
  private SignTypeEnum signType;

  public static final String JSON_PROPERTY_SIGN_ALGORITHM = "signAlgorithm";
  @javax.annotation.Nonnull
  private SignAlgorithmEnum signAlgorithm;

  public static final String JSON_PROPERTY_SIGN_MODE = "signMode";
  @javax.annotation.Nonnull
  private SignModeEnum signMode;

  public static final String JSON_PROPERTY_TIME_STAMP_INCLUDED = "timeStampIncluded";
  @javax.annotation.Nonnull
  private Boolean timeStampIncluded;

  public static final String JSON_PROPERTY_POLICY_INCLUDED = "policyIncluded";
  @javax.annotation.Nonnull
  private Boolean policyIncluded;

  public SignatureTypeInfo() {
  }

  public SignatureTypeInfo profileCode(@javax.annotation.Nonnull String profileCode) {
    
    this.profileCode = profileCode;
    return this;
  }

  /**
   * Codi del perfil de firma a la que pertany aquest tipus de firma.
   * @return profileCode
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PROFILE_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProfileCode() {
    return profileCode;
  }


  @JsonProperty(JSON_PROPERTY_PROFILE_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProfileCode(@javax.annotation.Nonnull String profileCode) {
    this.profileCode = profileCode;
  }

  public SignatureTypeInfo signOperation(@javax.annotation.Nonnull SignOperationEnum signOperation) {
    
    this.signOperation = signOperation;
    return this;
  }

  /**
   * Get signOperation
   * @return signOperation
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIGN_OPERATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SignOperationEnum getSignOperation() {
    return signOperation;
  }


  @JsonProperty(JSON_PROPERTY_SIGN_OPERATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignOperation(@javax.annotation.Nonnull SignOperationEnum signOperation) {
    this.signOperation = signOperation;
  }

  public SignatureTypeInfo signType(@javax.annotation.Nonnull SignTypeEnum signType) {
    
    this.signType = signType;
    return this;
  }

  /**
   * Get signType
   * @return signType
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIGN_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SignTypeEnum getSignType() {
    return signType;
  }


  @JsonProperty(JSON_PROPERTY_SIGN_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignType(@javax.annotation.Nonnull SignTypeEnum signType) {
    this.signType = signType;
  }

  public SignatureTypeInfo signAlgorithm(@javax.annotation.Nonnull SignAlgorithmEnum signAlgorithm) {
    
    this.signAlgorithm = signAlgorithm;
    return this;
  }

  /**
   * Get signAlgorithm
   * @return signAlgorithm
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIGN_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SignAlgorithmEnum getSignAlgorithm() {
    return signAlgorithm;
  }


  @JsonProperty(JSON_PROPERTY_SIGN_ALGORITHM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignAlgorithm(@javax.annotation.Nonnull SignAlgorithmEnum signAlgorithm) {
    this.signAlgorithm = signAlgorithm;
  }

  public SignatureTypeInfo signMode(@javax.annotation.Nonnull SignModeEnum signMode) {
    
    this.signMode = signMode;
    return this;
  }

  /**
   * Get signMode
   * @return signMode
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIGN_MODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SignModeEnum getSignMode() {
    return signMode;
  }


  @JsonProperty(JSON_PROPERTY_SIGN_MODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignMode(@javax.annotation.Nonnull SignModeEnum signMode) {
    this.signMode = signMode;
  }

  public SignatureTypeInfo timeStampIncluded(@javax.annotation.Nonnull Boolean timeStampIncluded) {
    
    this.timeStampIncluded = timeStampIncluded;
    return this;
  }

  /**
   * Indica si s&#39;ha afegit un segell de Temps durant la firma
   * @return timeStampIncluded
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TIME_STAMP_INCLUDED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getTimeStampIncluded() {
    return timeStampIncluded;
  }


  @JsonProperty(JSON_PROPERTY_TIME_STAMP_INCLUDED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTimeStampIncluded(@javax.annotation.Nonnull Boolean timeStampIncluded) {
    this.timeStampIncluded = timeStampIncluded;
  }

  public SignatureTypeInfo policyIncluded(@javax.annotation.Nonnull Boolean policyIncluded) {
    
    this.policyIncluded = policyIncluded;
    return this;
  }

  /**
   * Indica si inclou política de firma (true, EPES) o no (false)
   * @return policyIncluded
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_POLICY_INCLUDED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getPolicyIncluded() {
    return policyIncluded;
  }


  @JsonProperty(JSON_PROPERTY_POLICY_INCLUDED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPolicyIncluded(@javax.annotation.Nonnull Boolean policyIncluded) {
    this.policyIncluded = policyIncluded;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignatureTypeInfo signatureTypeInfo = (SignatureTypeInfo) o;
    return Objects.equals(this.profileCode, signatureTypeInfo.profileCode) &&
        Objects.equals(this.signOperation, signatureTypeInfo.signOperation) &&
        Objects.equals(this.signType, signatureTypeInfo.signType) &&
        Objects.equals(this.signAlgorithm, signatureTypeInfo.signAlgorithm) &&
        Objects.equals(this.signMode, signatureTypeInfo.signMode) &&
        Objects.equals(this.timeStampIncluded, signatureTypeInfo.timeStampIncluded) &&
        Objects.equals(this.policyIncluded, signatureTypeInfo.policyIncluded);
  }

  @Override
  public int hashCode() {
    return Objects.hash(profileCode, signOperation, signType, signAlgorithm, signMode, timeStampIncluded, policyIncluded);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignatureTypeInfo {\n");
    sb.append("    profileCode: ").append(toIndentedString(profileCode)).append("\n");
    sb.append("    signOperation: ").append(toIndentedString(signOperation)).append("\n");
    sb.append("    signType: ").append(toIndentedString(signType)).append("\n");
    sb.append("    signAlgorithm: ").append(toIndentedString(signAlgorithm)).append("\n");
    sb.append("    signMode: ").append(toIndentedString(signMode)).append("\n");
    sb.append("    timeStampIncluded: ").append(toIndentedString(timeStampIncluded)).append("\n");
    sb.append("    policyIncluded: ").append(toIndentedString(policyIncluded)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

