/*
 * Utilitats Firma Swagger v2
 * API Interna d'Utilitats Firma V2 que ofereix serveis de firma en servidor i validació de firmes.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: governdigital.firma@ibdigital.caib.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Algorisme de Firma. Valors:      • \&quot;SHA-1\&quot;      • \&quot;SHA-256\&quot;      • \&quot;SHA-384\&quot;      • \&quot;SHA-512\&quot;
 */
public enum SignAlgorithmConstants {
  
  /**
   *  
   */
  SIGN_ALGORITHM_SHA1("SHA-1"),
  
  /**
   *  
   */
  SIGN_ALGORITHM_SHA256("SHA-256"),
  
  /**
   *  
   */
  SIGN_ALGORITHM_SHA384("SHA-384"),
  
  /**
   *  
   */
  SIGN_ALGORITHM_SHA512("SHA-512");

  private String value;

  SignAlgorithmConstants(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static SignAlgorithmConstants fromValue(String value) {
    for (SignAlgorithmConstants b : SignAlgorithmConstants.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

