/*
 * Utilitats Firma Swagger v2
 * API Interna d'Utilitats Firma V2 que ofereix serveis de firma en servidor i validació de firmes.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: governdigital.firma@ibdigital.caib.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.ProcessStatus;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.SignPlugin;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.SignedFileInfo;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Resposta de la petició de firma en servidor
 */
@JsonPropertyOrder({
  SignedDocumentInformation.JSON_PROPERTY_SIGN_I_D,
  SignedDocumentInformation.JSON_PROPERTY_STATUS,
  SignedDocumentInformation.JSON_PROPERTY_SIGNED_FILE_INFO,
  SignedDocumentInformation.JSON_PROPERTY_SIGN_PLUGIN
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class SignedDocumentInformation {
  public static final String JSON_PROPERTY_SIGN_I_D = "signID";
  @javax.annotation.Nonnull
  private String signID;

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nonnull
  private ProcessStatus status;

  public static final String JSON_PROPERTY_SIGNED_FILE_INFO = "signedFileInfo";
  @javax.annotation.Nonnull
  private SignedFileInfo signedFileInfo;

  public static final String JSON_PROPERTY_SIGN_PLUGIN = "signPlugin";
  @javax.annotation.Nullable
  private SignPlugin signPlugin;

  public SignedDocumentInformation() {
  }

  public SignedDocumentInformation signID(@javax.annotation.Nonnull String signID) {
    
    this.signID = signID;
    return this;
  }

  /**
   * Identificador de la firma
   * @return signID
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIGN_I_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSignID() {
    return signID;
  }


  @JsonProperty(JSON_PROPERTY_SIGN_I_D)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignID(@javax.annotation.Nonnull String signID) {
    this.signID = signID;
  }

  public SignedDocumentInformation status(@javax.annotation.Nonnull ProcessStatus status) {
    
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ProcessStatus getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@javax.annotation.Nonnull ProcessStatus status) {
    this.status = status;
  }

  public SignedDocumentInformation signedFileInfo(@javax.annotation.Nonnull SignedFileInfo signedFileInfo) {
    
    this.signedFileInfo = signedFileInfo;
    return this;
  }

  /**
   * Get signedFileInfo
   * @return signedFileInfo
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIGNED_FILE_INFO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SignedFileInfo getSignedFileInfo() {
    return signedFileInfo;
  }


  @JsonProperty(JSON_PROPERTY_SIGNED_FILE_INFO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignedFileInfo(@javax.annotation.Nonnull SignedFileInfo signedFileInfo) {
    this.signedFileInfo = signedFileInfo;
  }

  public SignedDocumentInformation signPlugin(@javax.annotation.Nullable SignPlugin signPlugin) {
    
    this.signPlugin = signPlugin;
    return this;
  }

  /**
   * Get signPlugin
   * @return signPlugin
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGN_PLUGIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SignPlugin getSignPlugin() {
    return signPlugin;
  }


  @JsonProperty(JSON_PROPERTY_SIGN_PLUGIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignPlugin(@javax.annotation.Nullable SignPlugin signPlugin) {
    this.signPlugin = signPlugin;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignedDocumentInformation signedDocumentInformation = (SignedDocumentInformation) o;
    return Objects.equals(this.signID, signedDocumentInformation.signID) &&
        Objects.equals(this.status, signedDocumentInformation.status) &&
        Objects.equals(this.signedFileInfo, signedDocumentInformation.signedFileInfo) &&
        Objects.equals(this.signPlugin, signedDocumentInformation.signPlugin);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signID, status, signedFileInfo, signPlugin);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignedDocumentInformation {\n");
    sb.append("    signID: ").append(toIndentedString(signID)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    signedFileInfo: ").append(toIndentedString(signedFileInfo)).append("\n");
    sb.append("    signPlugin: ").append(toIndentedString(signPlugin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

