/*
 * Utilitats Firma Swagger v2
 * API Interna d'Utilitats Firma V2 que ofereix serveis de firma en servidor i validació de firmes.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: governdigital.firma@ibdigital.caib.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Tipus firma (PAdEs, CAdES, XAdES, ...).
 */
public enum SignTypeEnum {
  
  /**
   * PAdES
   */
  SIGN_TYPE_PADES(0),
  
  /**
   * XAdES
   */
  SIGN_TYPE_XADES(1),
  
  /**
   * CAdES
   */
  SIGN_TYPE_CADES(2),
  
  /**
   * SMIME
   */
  SMIME(3),
  
  /**
   * FacturaE
   */
  SIGN_TYPE_FACTURAE(4),
  
  /**
   * OOXML
   */
  SIGN_TYPE_OOXML(5),
  
  /**
   * ODF
   */
  SIGN_TYPE_ODF(6),
  
  /**
   * CAdES-ASiC-S
   */
  SIGN_TYPE_CADES_ASICS(7),
  
  /**
   * XAdES-ASiC-S
   */
  SIGN_TYPE_XADES_ASICS(8),
  
  /**
   * PKCS#1
   */
  SIGN_TYPE_PKCS(9);

  private Integer value;

  SignTypeEnum(Integer value) {
    this.value = value;
  }

  @JsonValue
  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static SignTypeEnum fromValue(Integer value) {
    for (SignTypeEnum b : SignTypeEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

