/*
 * Utilitats Firma Swagger v2
 * API Interna d'Utilitats Firma V2 que ofereix serveis de firma en servidor i validació de firmes.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: governdigital.firma@ibdigital.caib.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Possibles algorismes de firma.
 */
public enum SignAlgorithmEnum {
  
  /**
   * SHA1WITHRSA
   */
  SIGN_ALGORITHM_SHA1WITHRSA(0),
  
  /**
   * SHA256WITHRSA
   */
  SIGN_ALGORITHM_SHA256WITHRSA(1),
  
  /**
   * SHA384WITHRSA
   */
  SIGN_ALGORITHM_SHA384WITHRSA(2),
  
  /**
   * SHA512WITHRSA
   */
  SIGN_ALGORITHM_SHA512WITHRSA(3);

  private Integer value;

  SignAlgorithmEnum(Integer value) {
    this.value = value;
  }

  @JsonValue
  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static SignAlgorithmEnum fromValue(Integer value) {
    for (SignAlgorithmEnum b : SignAlgorithmEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

