/*
 * Utilitats Firma Swagger v2
 * API Interna d'Utilitats Firma V2 que ofereix serveis de firma en servidor i validació de firmes.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: governdigital.firma@ibdigital.caib.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.SignDocumentRequestV2;
import java.io.File;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SigndocumentRequest
 */
@JsonPropertyOrder({
  SigndocumentRequest.JSON_PROPERTY_SIGN_DOCUMENT_REQUEST,
  SigndocumentRequest.JSON_PROPERTY_FILE_TO_SIGN,
  SigndocumentRequest.JSON_PROPERTY_PREVIUS_SIGNATURE_DETACHED_FILE
})
@JsonTypeName("signdocument_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class SigndocumentRequest {
  public static final String JSON_PROPERTY_SIGN_DOCUMENT_REQUEST = "signDocumentRequest";
  @javax.annotation.Nonnull
  private SignDocumentRequestV2 signDocumentRequest;

  public static final String JSON_PROPERTY_FILE_TO_SIGN = "fileToSign";
  @javax.annotation.Nonnull
  private File fileToSign;

  public static final String JSON_PROPERTY_PREVIUS_SIGNATURE_DETACHED_FILE = "previusSignatureDetachedFile";
  @javax.annotation.Nullable
  private File previusSignatureDetachedFile;

  public SigndocumentRequest() {
  }

  public SigndocumentRequest signDocumentRequest(@javax.annotation.Nonnull SignDocumentRequestV2 signDocumentRequest) {
    
    this.signDocumentRequest = signDocumentRequest;
    return this;
  }

  /**
   * Get signDocumentRequest
   * @return signDocumentRequest
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIGN_DOCUMENT_REQUEST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SignDocumentRequestV2 getSignDocumentRequest() {
    return signDocumentRequest;
  }


  @JsonProperty(JSON_PROPERTY_SIGN_DOCUMENT_REQUEST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignDocumentRequest(@javax.annotation.Nonnull SignDocumentRequestV2 signDocumentRequest) {
    this.signDocumentRequest = signDocumentRequest;
  }

  public SigndocumentRequest fileToSign(@javax.annotation.Nonnull File fileToSign) {
    
    this.fileToSign = fileToSign;
    return this;
  }

  /**
   * Document a signar
   * @return fileToSign
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FILE_TO_SIGN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public File getFileToSign() {
    return fileToSign;
  }


  @JsonProperty(JSON_PROPERTY_FILE_TO_SIGN)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFileToSign(@javax.annotation.Nonnull File fileToSign) {
    this.fileToSign = fileToSign;
  }

  public SigndocumentRequest previusSignatureDetachedFile(@javax.annotation.Nullable File previusSignatureDetachedFile) {
    
    this.previusSignatureDetachedFile = previusSignatureDetachedFile;
    return this;
  }

  /**
   * Document detached. Només s&#39;usa per les validacions
   * @return previusSignatureDetachedFile
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PREVIUS_SIGNATURE_DETACHED_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public File getPreviusSignatureDetachedFile() {
    return previusSignatureDetachedFile;
  }


  @JsonProperty(JSON_PROPERTY_PREVIUS_SIGNATURE_DETACHED_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreviusSignatureDetachedFile(@javax.annotation.Nullable File previusSignatureDetachedFile) {
    this.previusSignatureDetachedFile = previusSignatureDetachedFile;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SigndocumentRequest signdocumentRequest = (SigndocumentRequest) o;
    return Objects.equals(this.signDocumentRequest, signdocumentRequest.signDocumentRequest) &&
        Objects.equals(this.fileToSign, signdocumentRequest.fileToSign) &&
        Objects.equals(this.previusSignatureDetachedFile, signdocumentRequest.previusSignatureDetachedFile);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signDocumentRequest, fileToSign, previusSignatureDetachedFile);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SigndocumentRequest {\n");
    sb.append("    signDocumentRequest: ").append(toIndentedString(signDocumentRequest)).append("\n");
    sb.append("    fileToSign: ").append(toIndentedString(fileToSign)).append("\n");
    sb.append("    previusSignatureDetachedFile: ").append(toIndentedString(previusSignatureDetachedFile)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

