/*
 * Utilitats Firma Swagger v2
 * API Interna d'Utilitats Firma V2 que ofereix serveis de firma en servidor i validació de firmes.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: governdigital.firma@ibdigital.caib.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.MultipartNameAndMime;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.SignedDocumentInformation;
import java.io.File;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SignedDocumentResponseMultipart
 */
@JsonPropertyOrder({
  SignedDocumentResponseMultipart.JSON_PROPERTY_SIGNED_DOCUMENT_INFORMATION,
  SignedDocumentResponseMultipart.JSON_PROPERTY_SIGNED_FILE,
  SignedDocumentResponseMultipart.JSON_PROPERTY_SIGNED_FILE_PART_INFO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class SignedDocumentResponseMultipart {
  public static final String JSON_PROPERTY_SIGNED_DOCUMENT_INFORMATION = "signedDocumentInformation";
  @javax.annotation.Nonnull
  private SignedDocumentInformation signedDocumentInformation;

  public static final String JSON_PROPERTY_SIGNED_FILE = "signedFile";
  @javax.annotation.Nullable
  private File signedFile;

  public static final String JSON_PROPERTY_SIGNED_FILE_PART_INFO = "signedFilePartInfo";
  @javax.annotation.Nullable
  private MultipartNameAndMime signedFilePartInfo;

  public SignedDocumentResponseMultipart() {
  }

  public SignedDocumentResponseMultipart signedDocumentInformation(@javax.annotation.Nonnull SignedDocumentInformation signedDocumentInformation) {
    
    this.signedDocumentInformation = signedDocumentInformation;
    return this;
  }

  /**
   * Get signedDocumentInformation
   * @return signedDocumentInformation
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIGNED_DOCUMENT_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SignedDocumentInformation getSignedDocumentInformation() {
    return signedDocumentInformation;
  }


  @JsonProperty(JSON_PROPERTY_SIGNED_DOCUMENT_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignedDocumentInformation(@javax.annotation.Nonnull SignedDocumentInformation signedDocumentInformation) {
    this.signedDocumentInformation = signedDocumentInformation;
  }

  public SignedDocumentResponseMultipart signedFile(@javax.annotation.Nullable File signedFile) {
    
    this.signedFile = signedFile;
    return this;
  }

  /**
   * Contingut del Document Signat
   * @return signedFile
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGNED_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public File getSignedFile() {
    return signedFile;
  }


  @JsonProperty(JSON_PROPERTY_SIGNED_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignedFile(@javax.annotation.Nullable File signedFile) {
    this.signedFile = signedFile;
  }

  public SignedDocumentResponseMultipart signedFilePartInfo(@javax.annotation.Nullable MultipartNameAndMime signedFilePartInfo) {
    
    this.signedFilePartInfo = signedFilePartInfo;
    return this;
  }

  /**
   * Get signedFilePartInfo
   * @return signedFilePartInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGNED_FILE_PART_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MultipartNameAndMime getSignedFilePartInfo() {
    return signedFilePartInfo;
  }


  @JsonProperty(JSON_PROPERTY_SIGNED_FILE_PART_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignedFilePartInfo(@javax.annotation.Nullable MultipartNameAndMime signedFilePartInfo) {
    this.signedFilePartInfo = signedFilePartInfo;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignedDocumentResponseMultipart signedDocumentResponseMultipart = (SignedDocumentResponseMultipart) o;
    return Objects.equals(this.signedDocumentInformation, signedDocumentResponseMultipart.signedDocumentInformation) &&
        Objects.equals(this.signedFile, signedDocumentResponseMultipart.signedFile) &&
        Objects.equals(this.signedFilePartInfo, signedDocumentResponseMultipart.signedFilePartInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signedDocumentInformation, signedFile, signedFilePartInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SignedDocumentResponseMultipart {\n");
    sb.append("    signedDocumentInformation: ").append(toIndentedString(signedDocumentInformation)).append("\n");
    sb.append("    signedFile: ").append(toIndentedString(signedFile)).append("\n");
    sb.append("    signedFilePartInfo: ").append(toIndentedString(signedFilePartInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

