/*
 * Utilitats Firma Swagger v2
 * API Interna d'Utilitats Firma V2 que ofereix serveis de firma en servidor i validació de firmes.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: governdigital.firma@ibdigital.caib.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.UpgradedFileInfo;
import java.io.File;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Resposta de l&#39;actualització de signatura amb informació 
 */
@JsonPropertyOrder({
  UpgradeResponseMultipart.JSON_PROPERTY_UPGRADED_FILE,
  UpgradeResponseMultipart.JSON_PROPERTY_UPGRADED_FILE_INFO
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class UpgradeResponseMultipart {
  public static final String JSON_PROPERTY_UPGRADED_FILE = "upgradedFile";
  @javax.annotation.Nullable
  private File upgradedFile;

  public static final String JSON_PROPERTY_UPGRADED_FILE_INFO = "upgradedFileInfo";
  @javax.annotation.Nullable
  private UpgradedFileInfo upgradedFileInfo;

  public UpgradeResponseMultipart() {
  }

  public UpgradeResponseMultipart upgradedFile(@javax.annotation.Nullable File upgradedFile) {
    
    this.upgradedFile = upgradedFile;
    return this;
  }

  /**
   * Fitxer amb la signatura actualitzada
   * @return upgradedFile
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPGRADED_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public File getUpgradedFile() {
    return upgradedFile;
  }


  @JsonProperty(JSON_PROPERTY_UPGRADED_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpgradedFile(@javax.annotation.Nullable File upgradedFile) {
    this.upgradedFile = upgradedFile;
  }

  public UpgradeResponseMultipart upgradedFileInfo(@javax.annotation.Nullable UpgradedFileInfo upgradedFileInfo) {
    
    this.upgradedFileInfo = upgradedFileInfo;
    return this;
  }

  /**
   * Get upgradedFileInfo
   * @return upgradedFileInfo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPGRADED_FILE_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UpgradedFileInfo getUpgradedFileInfo() {
    return upgradedFileInfo;
  }


  @JsonProperty(JSON_PROPERTY_UPGRADED_FILE_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpgradedFileInfo(@javax.annotation.Nullable UpgradedFileInfo upgradedFileInfo) {
    this.upgradedFileInfo = upgradedFileInfo;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpgradeResponseMultipart upgradeResponseMultipart = (UpgradeResponseMultipart) o;
    return Objects.equals(this.upgradedFile, upgradeResponseMultipart.upgradedFile) &&
        Objects.equals(this.upgradedFileInfo, upgradeResponseMultipart.upgradedFileInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(upgradedFile, upgradedFileInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpgradeResponseMultipart {\n");
    sb.append("    upgradedFile: ").append(toIndentedString(upgradedFile)).append("\n");
    sb.append("    upgradedFileInfo: ").append(toIndentedString(upgradedFileInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

