/*
 * Utilitats Firma Swagger v2
 * API Interna d'Utilitats Firma V2 que ofereix serveis de firma en servidor i validació de firmes.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: governdigital.firma@ibdigital.caib.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.File;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UpgradeRequestMultipart
 */
@JsonPropertyOrder({
  UpgradeRequestMultipart.JSON_PROPERTY_PROFILE_CODE,
  UpgradeRequestMultipart.JSON_PROPERTY_SIGNATURE,
  UpgradeRequestMultipart.JSON_PROPERTY_DETACHED_DOCUMENT,
  UpgradeRequestMultipart.JSON_PROPERTY_TARGET_CERTIFICATE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class UpgradeRequestMultipart {
  public static final String JSON_PROPERTY_PROFILE_CODE = "profileCode";
  @javax.annotation.Nullable
  private String profileCode;

  public static final String JSON_PROPERTY_SIGNATURE = "signature";
  @javax.annotation.Nullable
  private File signature;

  public static final String JSON_PROPERTY_DETACHED_DOCUMENT = "detachedDocument";
  @javax.annotation.Nullable
  private File detachedDocument;

  public static final String JSON_PROPERTY_TARGET_CERTIFICATE = "targetCertificate";
  @javax.annotation.Nullable
  private File targetCertificate;

  public UpgradeRequestMultipart() {
  }

  public UpgradeRequestMultipart profileCode(@javax.annotation.Nullable String profileCode) {
    
    this.profileCode = profileCode;
    return this;
  }

  /**
   * Get profileCode
   * @return profileCode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROFILE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProfileCode() {
    return profileCode;
  }


  @JsonProperty(JSON_PROPERTY_PROFILE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProfileCode(@javax.annotation.Nullable String profileCode) {
    this.profileCode = profileCode;
  }

  public UpgradeRequestMultipart signature(@javax.annotation.Nullable File signature) {
    
    this.signature = signature;
    return this;
  }

  /**
   * Get signature
   * @return signature
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public File getSignature() {
    return signature;
  }


  @JsonProperty(JSON_PROPERTY_SIGNATURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignature(@javax.annotation.Nullable File signature) {
    this.signature = signature;
  }

  public UpgradeRequestMultipart detachedDocument(@javax.annotation.Nullable File detachedDocument) {
    
    this.detachedDocument = detachedDocument;
    return this;
  }

  /**
   * Get detachedDocument
   * @return detachedDocument
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DETACHED_DOCUMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public File getDetachedDocument() {
    return detachedDocument;
  }


  @JsonProperty(JSON_PROPERTY_DETACHED_DOCUMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDetachedDocument(@javax.annotation.Nullable File detachedDocument) {
    this.detachedDocument = detachedDocument;
  }

  public UpgradeRequestMultipart targetCertificate(@javax.annotation.Nullable File targetCertificate) {
    
    this.targetCertificate = targetCertificate;
    return this;
  }

  /**
   * Get targetCertificate
   * @return targetCertificate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TARGET_CERTIFICATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public File getTargetCertificate() {
    return targetCertificate;
  }


  @JsonProperty(JSON_PROPERTY_TARGET_CERTIFICATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTargetCertificate(@javax.annotation.Nullable File targetCertificate) {
    this.targetCertificate = targetCertificate;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpgradeRequestMultipart upgradeRequestMultipart = (UpgradeRequestMultipart) o;
    return Objects.equals(this.profileCode, upgradeRequestMultipart.profileCode) &&
        Objects.equals(this.signature, upgradeRequestMultipart.signature) &&
        Objects.equals(this.detachedDocument, upgradeRequestMultipart.detachedDocument) &&
        Objects.equals(this.targetCertificate, upgradeRequestMultipart.targetCertificate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(profileCode, signature, detachedDocument, targetCertificate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpgradeRequestMultipart {\n");
    sb.append("    profileCode: ").append(toIndentedString(profileCode)).append("\n");
    sb.append("    signature: ").append(toIndentedString(signature)).append("\n");
    sb.append("    detachedDocument: ").append(toIndentedString(detachedDocument)).append("\n");
    sb.append("    targetCertificate: ").append(toIndentedString(targetCertificate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

