/*
 * Utilitats Firma Swagger v2
 * API Interna d'Utilitats Firma V2 que ofereix serveis de firma en servidor i validació de firmes.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: governdigital.firma@ibdigital.caib.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.UpgradedFileInfoV2;
import java.io.File;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Resposta de l&#39;actualització de signatura amb informació 
 */
@JsonPropertyOrder({
  UpgradeResponseMultipart.JSON_PROPERTY_UPGRADED_FILE,
  UpgradeResponseMultipart.JSON_PROPERTY_UPGRADED_FILE_INFO_V2
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class UpgradeResponseMultipart {
  public static final String JSON_PROPERTY_UPGRADED_FILE = "upgradedFile";
  @javax.annotation.Nullable
  private File upgradedFile;

  public static final String JSON_PROPERTY_UPGRADED_FILE_INFO_V2 = "upgradedFileInfoV2";
  @javax.annotation.Nullable
  private UpgradedFileInfoV2 upgradedFileInfoV2;

  public UpgradeResponseMultipart() {
  }

  public UpgradeResponseMultipart upgradedFile(@javax.annotation.Nullable File upgradedFile) {
    
    this.upgradedFile = upgradedFile;
    return this;
  }

  /**
   * Fitxer amb la signatura actualitzada
   * @return upgradedFile
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPGRADED_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public File getUpgradedFile() {
    return upgradedFile;
  }


  @JsonProperty(JSON_PROPERTY_UPGRADED_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpgradedFile(@javax.annotation.Nullable File upgradedFile) {
    this.upgradedFile = upgradedFile;
  }

  public UpgradeResponseMultipart upgradedFileInfoV2(@javax.annotation.Nullable UpgradedFileInfoV2 upgradedFileInfoV2) {
    
    this.upgradedFileInfoV2 = upgradedFileInfoV2;
    return this;
  }

  /**
   * Get upgradedFileInfoV2
   * @return upgradedFileInfoV2
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPGRADED_FILE_INFO_V2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UpgradedFileInfoV2 getUpgradedFileInfoV2() {
    return upgradedFileInfoV2;
  }


  @JsonProperty(JSON_PROPERTY_UPGRADED_FILE_INFO_V2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpgradedFileInfoV2(@javax.annotation.Nullable UpgradedFileInfoV2 upgradedFileInfoV2) {
    this.upgradedFileInfoV2 = upgradedFileInfoV2;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpgradeResponseMultipart upgradeResponseMultipart = (UpgradeResponseMultipart) o;
    return Objects.equals(this.upgradedFile, upgradeResponseMultipart.upgradedFile) &&
        Objects.equals(this.upgradedFileInfoV2, upgradeResponseMultipart.upgradedFileInfoV2);
  }

  @Override
  public int hashCode() {
    return Objects.hash(upgradedFile, upgradedFileInfoV2);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpgradeResponseMultipart {\n");
    sb.append("    upgradedFile: ").append(toIndentedString(upgradedFile)).append("\n");
    sb.append("    upgradedFileInfoV2: ").append(toIndentedString(upgradedFileInfoV2)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

