/*
 * Utilitats Firma Swagger v2
 * API Interna d'Utilitats Firma V2 que ofereix serveis de firma en servidor i validació de firmes.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: governdigital.firma@ibdigital.caib.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model.SignatureRequestedInformation;
import java.io.File;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ValidateSignatureRequest
 */
@JsonPropertyOrder({
  ValidateSignatureRequest.JSON_PROPERTY_SIGNATURE_REQUESTED_INFORMATION,
  ValidateSignatureRequest.JSON_PROPERTY_SIGNATURE_DOCUMENT,
  ValidateSignatureRequest.JSON_PROPERTY_DETACHED_DOCUMENT
})
@JsonTypeName("validateSignature_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class ValidateSignatureRequest {
  public static final String JSON_PROPERTY_SIGNATURE_REQUESTED_INFORMATION = "signatureRequestedInformation";
  @javax.annotation.Nonnull
  private SignatureRequestedInformation signatureRequestedInformation;

  public static final String JSON_PROPERTY_SIGNATURE_DOCUMENT = "signatureDocument";
  @javax.annotation.Nonnull
  private File signatureDocument;

  public static final String JSON_PROPERTY_DETACHED_DOCUMENT = "detachedDocument";
  @javax.annotation.Nullable
  private File detachedDocument;

  public ValidateSignatureRequest() {
  }

  public ValidateSignatureRequest signatureRequestedInformation(@javax.annotation.Nonnull SignatureRequestedInformation signatureRequestedInformation) {
    
    this.signatureRequestedInformation = signatureRequestedInformation;
    return this;
  }

  /**
   * Get signatureRequestedInformation
   * @return signatureRequestedInformation
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIGNATURE_REQUESTED_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SignatureRequestedInformation getSignatureRequestedInformation() {
    return signatureRequestedInformation;
  }


  @JsonProperty(JSON_PROPERTY_SIGNATURE_REQUESTED_INFORMATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignatureRequestedInformation(@javax.annotation.Nonnull SignatureRequestedInformation signatureRequestedInformation) {
    this.signatureRequestedInformation = signatureRequestedInformation;
  }

  public ValidateSignatureRequest signatureDocument(@javax.annotation.Nonnull File signatureDocument) {
    
    this.signatureDocument = signatureDocument;
    return this;
  }

  /**
   * Signatura
   * @return signatureDocument
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIGNATURE_DOCUMENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public File getSignatureDocument() {
    return signatureDocument;
  }


  @JsonProperty(JSON_PROPERTY_SIGNATURE_DOCUMENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignatureDocument(@javax.annotation.Nonnull File signatureDocument) {
    this.signatureDocument = signatureDocument;
  }

  public ValidateSignatureRequest detachedDocument(@javax.annotation.Nullable File detachedDocument) {
    
    this.detachedDocument = detachedDocument;
    return this;
  }

  /**
   * Document detached.
   * @return detachedDocument
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DETACHED_DOCUMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public File getDetachedDocument() {
    return detachedDocument;
  }


  @JsonProperty(JSON_PROPERTY_DETACHED_DOCUMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDetachedDocument(@javax.annotation.Nullable File detachedDocument) {
    this.detachedDocument = detachedDocument;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidateSignatureRequest validateSignatureRequest = (ValidateSignatureRequest) o;
    return Objects.equals(this.signatureRequestedInformation, validateSignatureRequest.signatureRequestedInformation) &&
        Objects.equals(this.signatureDocument, validateSignatureRequest.signatureDocument) &&
        Objects.equals(this.detachedDocument, validateSignatureRequest.detachedDocument);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signatureRequestedInformation, signatureDocument, detachedDocument);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidateSignatureRequest {\n");
    sb.append("    signatureRequestedInformation: ").append(toIndentedString(signatureRequestedInformation)).append("\n");
    sb.append("    signatureDocument: ").append(toIndentedString(signatureDocument)).append("\n");
    sb.append("    detachedDocument: ").append(toIndentedString(detachedDocument)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

