/*
 * Utilitats Firma Swagger v2
 * API Interna d'Utilitats Firma V2 que ofereix serveis de firma en servidor i validació de firmes.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: governdigital.firma@ibdigital.caib.es
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.utilitatsfirma.api.interna.client.utilitatsfirma.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Estats de la validació d&#39;una firma:     • \&quot;SIGNATURE_VALID\&quot;     • \&quot;SIGNATURE_ERROR\&quot; 
 */
public enum ValidationStatusConstants {
  
  /**
   *  
   */
  SIGNATURE_VALID(1),
  
  /**
   *  
   */
  SIGNATURE_ERROR(-1),
  
  /**
   *  
   */
  SIGNATURE_INVALID(-2);

  private Integer value;

  ValidationStatusConstants(Integer value) {
    this.value = value;
  }

  @JsonValue
  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ValidationStatusConstants fromValue(Integer value) {
    for (ValidationStatusConstants b : ValidationStatusConstants.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

